### ISSUE TITLE
Adding additional performance metrics

### ISSUE THREAD

**Issue by stefaneft** [samisalreadytaken/csgo-benchmark#3]
Hello, 
Would it be possible to add additional results to the console output (for example lowest fps, average frametime, highest frametime)?
Thank you so much for your work so far!

**Comment by samisalreadytaken** [comment]
Unfortunately there is just no way of reading any type of frame data without an external tool. This script only prints around the engine benchmark output, the values are inaccessible.

If you have the time, you can record your own demo which you would benchmark using the `timedemo` console command, which exports 2 csv files that include more details. The averages are exported into the `sourcebench_<GPU>_<USER>.csv` file.
