### ISSUE TITLE
Adding 64 player models to help benchmark 64 player servers

### ISSUE THREAD

**Issue by fgf-4** [samisalreadytaken/csgo-benchmark#4]
Hi,
first, thank you for your benchmark script. 

There are many 64 players servers where the FPS drops often to 30 FPS, depending on how many players are in view. Maybe you can add a 64 player models benchmark to help benchmark this.

**Comment by samisalreadytaken** [comment]
If you need such niche modifications, you can easily add them yourself. To add more player models you can use the `bm_mdl` console command to add your current position and angles to a list, use `bm_list` to print them all, then copy paste them in whatever map's setup function in the `benchmark_res.nut` file.

This is a general purpose script for testing map performance, not server. 64 player servers usually have so much else going on, trying to measure that offline would be irrelevant, and more player models would not be reflective of the effects of more players.
