### ISSUE TITLE
can not benchmark in a workshop map (de_dust2_minimal)

### ISSUE THREAD

**Issue by Poiob** [samisalreadytaken/csgo-benchmark#6]
this map just simplify de_dust2 so I want to benchmark it with the way u benchmark dust2
I copy bm_de_dust2.nut and rename it as bm_de_dust2_minimal.nut
In benchmark_res.nut ,I copy the [function Setup_de_dust2()] and rename it as  [function Setup_de_dust2_minimal()]

console said [[!] Map data not found for 'de_dust2_minimal'] XD

**Comment by samisalreadytaken** [comment]
There are 2 more changes required: inside the `bm_de_dust2_minimal.nut` file, and at the bottom of the `benchmark_res.nut` file.

Reading this I realised it can be too much and confusing. I just pushed an update that only requires the file with the map name. So, your current changes should be enough using 1.4.6.
