### ISSUE TITLE
Question: Looping

### ISSUE THREAD

**Issue by DubMFG** [samisalreadytaken/csgo-benchmark#7]
Is it possible to add the ability to loop this function endlessly to simulate a gaming load on a PC?

**Comment by samisalreadytaken** [comment]
Sorry for the late reply, I added `SetLooping()` to simply loop back to the start on playback end and execute the setup function again. It needs to be placed inside the setup function of the map.

For de_dust2, it would be inside `bm_de_dust2.nut`,

```cs
function Setup()
{
	SetLooping( true )
...
```
